payment:
   service:
     url : http://localhost:8764/payment/price?price=
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
